name: mobile_design_task
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.4.1 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  iconsax:
  get:
  dio:
  shared_preferences:
  intl:
  loading_animation_widget:
  lottie:
  custom_navigation_bar:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons:
  flutter_native_splash:

flutter_native_splash:
  image: assets/icons/png/transparent_app_icon.png
  color: "#f9f9f9"
  image_dark: assets/icons/png/transparent_app_icon.png
  color_dark: "#000000"

flutter_launcher_icons:
  android: "launcher_icon"
  remove_alpha_ios: true
  ios: true
  image_path: "assets/icons/png/dark_app_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/png/
    - assets/images/svg/
    - assets/icons/png/
    - assets/icons/svg/
    - assets/animations/

  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter/Inter-VariableFont_slnt,wght.ttf
        - asset: fonts/Inter/static/Inter-Black.ttf
        - asset: fonts/Inter/static/Inter-Bold.ttf
        - asset: fonts/Inter/static/Inter-ExtraBold.ttf
        - asset: fonts/Inter/static/Inter-ExtraLight.ttf
        - asset: fonts/Inter/static/Inter-Light.ttf
        - asset: fonts/Inter/static/Inter-Medium.ttf
        - asset: fonts/Inter/static/Inter-Regular.ttf
        - asset: fonts/Inter/static/Inter-SemiBold.ttf
        - asset: fonts/Inter/static/Inter-Thin.ttf
          weight: 700
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
